#!/bin/sh
PGPASSWORD=$POSTGRES_PASSWORD psql -d postgres << EOF
  CREATE DATABASE $APP_DB_DATABASE;
  CREATE USER $APP_DB_USERNAME WITH ENCRYPTED PASSWORD '${APP_DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_DATABASE TO $APP_DB_USERNAME;
EOF

PGPASSWORD=$POSTGRES_PASSWORD psql -U postgres -d $APP_DB_DATABASE -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
